# Simple workflow for deploying static content to GitHub Pages
name: Deploy gh-pages

# Only trigger, when the build workflow succeeded
# 
on:
  workflow_run:
    workflows: ["Mkdocs Build & Upload CI"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  download_artifact:
    runs-on: ubuntu-latest
    steps:  # https://github.com/dawidd6/action-download-artifact#usage
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: mkdocs_build_upload_ci.yml
          workflow_conclusion: success
          name: mkdocs_build_artifact
          if_no_artifact_found: fail
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: download_artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '/site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact_name: mkdocs_build_artifact
