name: Mkdocs Build & Upload CI
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs "mkdocstrings[python]" mkdocs-material 
      - run: mkdocs build
      - name: Commit to Github Pages
        uses: EndBug/add-and-commit@v9.1.1
        id: commit_gh_pages
        with:
          add: 'site'
          new_branch: 'gh-pages'
